FriendRequestCell의 timeStamp 구현
wafflestudio19-5/team9-iOS pull request #70
Opened 2022-01-26 14:00 UTC by KWSMooBang

FriendRequestCell의 timeStamp를 구현했습니다.

2022-01-26 15:40 UTC, peng-u-0807 requested changes
constraint 기준이 cell의 상단이 아니고 유저 이름 label의 상단이어야 합니다. 수정 부탁드려요! 그리고 cell 사이의 separator도 삭제 부탁드립니다

2022-01-27 00:54 UTC, KWSMooBang commented
@peng-u-0807 시간을 표시하는 레이블의 위치가 이름 레이블 아래에 있어야 된다는 말씀이신가요?

2022-01-27 02:11 UTC, peng-u-0807 commented
@KWSMooBang timestamp의 top anchor가 contentView를 기준으로 하는 것이 아니라 authorLabel의 top anchor을 기준으로 해야된다는 뜻이었습니다! 실제 페이스북 화면 확인해보시면 알 수 있습니다

2022-01-27 05:57 UTC, peng-u-0807 approved these changes

2022-01-27 05:58 UTC, merged